### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by J-C-B** [dlopes7/monitoria#1]
Hi,

I'd like to provide some instructions by way of howto in the readme - if you can throw me some rough notes i can format, test etc then pull request? i'd like to get this going on my mac but have never used Django before so would like to help others and myself :)

i have

```
sudo pip install Django
```

cd into the folder then

```
python manage.py runserver
```

but get this issue

```
maccers$ python manage.py 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_tables2

```

**Comment by J-C-B** [comment]
also i found you via this post in case you are wondering

https://www.linkedin.com/pulse/free-webpage-tests-python-webpagetestorg-david-ribeiro-lopes

i was looking for a python tool :)
